import { COUNTRIES } from './countries';

export const QBE_PROMPTS = [
  {
    tabName: 'General',
    control: 'generalInfo',
    items: [
      {
        sectionName: 'General Information',
        subItems: [
          {
            promptId: '',
            promptName: 'Receipt Date',
            type: 'group',
            filter: false,
            grid: false,
            placeholder: '',
            group: true,
            groupItems: [
              {
                promptId: '',
                promptName: 'Receipt Date Type',
                type: 'dropdown',
                control: 'receiptDateType',
                value: [
                  { name: 'Initial Receipt Date', value: 1 },
                  { name: 'Initial or follow-up Receipt Date', value: 2 },
                  {
                    name: 'Initial or significant follow-up Receipt Date',
                    value: 3,
                  },
                ],
                filter: false,
                grid: false,
                placeholder: 'Select Receipt Date Type',
              },
              {
                promptId: '',
                promptName: 'Receipt Date - Start Date',
                type: 'calendar',
                filter: false,
                grid: false,
                control: 'receiptStartDate',
                placeholder: 'Select Start Date',
              },
              {
                promptId: '',
                promptName: 'Receipt Date - End Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select End Date',
                control: 'receiptEndDate',
              },
            ],
          },
          {
            promptId: '',
            promptName: 'Safety Date',
            type: 'group',
            filter: false,
            grid: false,
            placeholder: '',
            group: true,
            groupItems: [
              {
                promptId: '',
                promptName: 'Safety Date Type',
                type: 'dropdown',
                value: [
                  { name: 'Initial Safety Date', value: 1 },
                  { name: 'Initial or follow-up Safety Date', value: 2 },
                  {
                    name: 'Initial or significant follow-up Safety Date',
                    value: 3,
                  },
                ],
                filter: false,
                grid: false,
                control: 'safetyDateType',
                placeholder: 'Select Safety Date Type',
              },
              {
                promptId: '',
                promptName: 'Safety Date - Start Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select Start Date',
                control: 'safetyStartDate',
              },
              {
                promptId: '',
                promptName: 'Safety Date - End Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select End Date',
                control: 'safetyEndDate',
              },
            ],
          },
          {
            promptId: '',
            promptName: 'Report Type',
            type: 'multiselect',
            filter: true,
            group: false,
            groupItems: [],
            value: [
              { name: 'Literature', value: 1 },
              { name: 'Regulatory Authority', value: 2 },
              { name: 'Spontaneous', value: 3 },
              { name: 'Spontaneous Literature', value: 4 },
              { name: 'Sponsored Trial', value: 5 },
              { name: 'Post Marketing Surv.', value: 6 },
              { name: 'Compassionate Use', value: 7 },
              { name: 'Other', value: 8 },
              { name: 'Not Available to Sender', value: 9 },
              { name: 'Non-Sponsored Trial', value: 10 },
              { name: 'Non-Interventional Study', value: 11 },
              { name: 'Stimulated Spontaneous', value: 12 },
            ],
            placeholder: 'Select Report Type',
            grid: false,
            control: 'reportType',
          },
          {
            promptId: '',
            promptName: 'Country of Incidence',
            type: 'multiselect',
            filter: true,
            group: false,
            groupItems: [],
            value: COUNTRIES,
            placeholder: 'Select Country of Incidence',
            grid: false,
            control: 'countryOfIncidence',
          },
          {
            promptId: '',
            promptName: 'Medically Confirmed',
            type: 'dropdown',
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'All', value: 3 },
            ],
            filter: false,
            grid: false,
            placeholder: 'Select Medically Confirmed',
            group: false,
            groupItems: [],
            control: 'medicallyConfirmed',
          },
          {
            promptId: '',
            promptName: 'Invalid Case (calculated)',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Invalid Case (calculated)',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'All', value: 3 },
            ],
            control: 'invalidCaseCalculated',
          },
          {
            promptId: '',
            promptName: 'Case Status',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Case Status',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'All', value: 3 },
            ],
            control: 'caseStatus',
          },
          {
            promptId: '',
            promptName: 'SUSAR Case (calculated)',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select SUSAR Case (calculated)',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'All', value: 3 },
            ],
            control: 'susarCaseCalculated',
          },
          {
            promptId: '',
            promptName: 'Case Priority',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Case Priority',
            group: false,
            groupItems: [],
            value: [
              { name: 'Expedited' },
              { name: 'Invalid' },
              { name: 'Not Reportable' },
            ],
            control: 'casePriority',
          },
        ],
      },
      {
        sectionName: 'Reporter Information',
        subItems: [
          {
            promptId: '',
            promptName: 'Reporter Country',
            type: 'dropdown',
            filter: true,
            grid: false,
            placeholder: 'Select Reporter Country',
            group: false,
            groupItems: [],
            value: COUNTRIES,
            control: 'reporterCountry',
          },
          {
            promptId: '',
            promptName: 'Reporter HCP',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Reporter HCP',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'Unknown', value: 3 },
            ],
            control: 'reporterHcp',
          },
        ],
      },
    ],
  },
  {
    tabName: 'Patient',
    control: 'patientInfo',
    items: [
      {
        sectionName: 'Patient Information',
        subItems: [
          {
            promptId: '',
            promptName: 'Patient Age Group',
            type: 'dropdown',
            filter: true,
            group: false,
            groupItems: [],
            placeholder: 'Select Patient Age Group',
            value: [
              { name: 'Adolescent', value: 1 },
              { name: 'Adult', value: 2 },
              { name: 'Child', value: 3 },
              { name: 'Elderly', value: 4 },
              { name: 'Foetus', value: 5 },
              { name: 'Infant', value: 6 },
              { name: 'Neonate', value: 7 },
              { name: 'Unknown', value: 8 },
            ],
            grid: false,
            control: 'patientAgeGroup',
          },
          {
            promptId: '',
            promptName: 'Patient Race',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Patient Race',
            group: false,
            groupItems: [],
            value: [
              { name: 'African American' },
              { name: 'American Indian or Alaska Native' },
              { name: 'Asian' },
              { name: 'Black' },
              { name: 'Caucasian' },
              { name: 'Native Hawaiian or Other Pacific Islander' },
              { name: 'White' },
              { name: 'Other' },
              { name: 'Unknown' },
            ],
            control: 'patientRace',
          },
          {
            promptId: '',
            promptName: 'Patient Gender',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Patient Gender',
            group: false,
            groupItems: [],
            value: [
              { name: 'Female' },
              { name: 'Intersex' },
              { name: 'Male' },
              { name: 'Other' },
              { name: 'Transgender' },
              { name: 'UNK' },
              { name: 'Undeclared' },
            ],
            control: 'patientGender',
          },
          {
            promptId: '',
            promptName: 'Patient Pregnant',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes' },
              { name: 'No' },
              { name: 'Unknown' },
              { name: 'N/A' },
            ],
            control: 'patientPregnant',
          },
          {
            promptId: '',
            promptName: 'Patient Age Range (Years)',
            type: 'range',
            filter: false,
            grid: false,
            placeholder: 'Select Patient Age Range (Years)',
            group: false,
            groupItems: [],
            control: 'patientAgeRange',
          },
        ],
      },
    ],
  },
  {
    tabName: 'Product',
    control: 'productInfo',
    items: [
      {
        sectionName: 'Product Information',
        subItems: [
          {
            promptId: '',
            promptName: 'Drug Type',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Drug Type',
            group: false,
            groupItems: [],
            value: [
              { name: 'All' },
              { name: 'Suspect' },
              { name: 'Concomitant' },
              { name: 'Treatment' },
            ],
            control: 'drugType',
          },
          {
            promptId: '',
            promptName: 'Off Label Use',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Off Label Use',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'All', value: 3 },
            ],
            control: 'offLabelUse',
          },
          {
            promptId: '',
            promptName: 'Overdose',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Overdose',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'All', value: 3 },
            ],
            control: 'overdose',
          },
          {
            promptId: '',
            promptName: 'Product Name',
            type: 'textAreaButton',
            buttonName: 'Product Selector',
            filter: false,
            grid: true,
            placeholder: 'Select Product from Product Selector',
            onButtonSelect: 'productSelection',
            group: false,
            groupItems: [],
            control: 'productName',
          },
        ],
      },
      {
        sectionName: 'Dosage Information',
        subItems: [
          {
            promptId: '',
            promptName: 'Batch/Lot #',
            type: 'text',
            filter: false,
            grid: false,
            placeholder: 'Enter Batch/Lot in %',
            group: false,
            groupItems: [],
            control: 'batch/lot',
          },
        ],
      },
    ],
  },
  {
    tabName: 'Event',
    control: 'eventInfo',
    items: [
      {
        sectionName: 'Event Information',
        subItems: [
          {
            promptId: '',
            promptName: 'Event Receipt Date',
            type: 'group',
            group: true,
            grid: false,
            placeholder: '',
            filter: false,
            groupItems: [
              {
                promptId: '',
                promptName: 'Event Receipt Date - Start Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select Start Date',
                control: 'eventReceiptStartDate',
              },
              {
                promptId: '',
                promptName: 'Event Receipt Date - End Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select End Date',
                control: 'eventReceiptEndDate',
              },
            ],
          },
          {
            promptId: '',
            promptName: 'Event Seriousness',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Event Seriousness',
            group: false,
            groupItems: [],
            value: [
              { name: 'Yes', value: 1 },
              { name: 'No', value: 2 },
              { name: 'All', value: 3 },
            ],
            control: 'eventSeriousness',
          },
          {
            promptId: '',
            promptName: 'Event Seriousness Criteria',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Event Seriousness Criteria',
            group: false,
            groupItems: [],
            value: [
              { name: 'Congenital Anomaly' },
              { name: 'Death' },
              { name: 'Disability' },
              { name: 'Hospitalized' },
              { name: 'Intervention Required' },
              { name: 'Life-threatening' },
              { name: 'Medically Significant' },
              { name: 'Other' },
            ],
            control: 'eventSeriousnessCriteria',
          },
          {
            promptId: '',
            promptName: 'Event Onset',
            type: 'group',
            group: true,
            groupItems: [
              {
                promptId: '',
                promptName: 'Event Onset - Start Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select Start Date',
                control: 'eventOnsetStartDate',
              },
              {
                promptId: '',
                promptName: 'Event Onset - End Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select End Date',
                control: 'eventOnsetEndDate',
              },
            ],
          },
          {
            promptId: '',
            promptName: 'Adverse Event',
            type: 'textAreaButton',
            buttonName: 'AE Selector',
            filter: false,
            grid: true,
            onButtonSelect: 'adverseEventSelection',
            group: false,
            groupItems: [],
            placeholder: 'Select AE from AE Selector',
            control: 'adverseEvent',
          },
        ],
      },
      {
        sectionName: 'Product - Event Assessment',
        subItems: [
          {
            promptId: '',
            promptName: 'Report Causality',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Report Causality',
            group: false,
            groupItems: [],
            value: [
              { name: 'Almost Certain', value: 1 },
              { name: 'None', value: 2 },
              { name: 'Not Related', value: 3 },
              { name: 'Not Reported', value: 4 },
              { name: 'Possible', value: 5 },
              { name: 'Probable', value: 6 },
              { name: 'Unknown', value: 7 },
              { name: 'Unlikely', value: 8 },
            ],
            control: 'reportCausality',
          },
          {
            promptId: '',
            promptName: 'Listedness',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Listedness',
            group: false,
            groupItems: [],
            value: [
              { name: 'Listed', value: 1 },
              { name: 'Unknown', value: 2 },
              { name: 'Unlisted', value: 3 },
            ],
            control: 'listedness',
          },
          {
            promptId: '',
            promptName: 'Listedness CORE',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Listedness CORE',
            group: false,
            groupItems: [],
            value: [
              { name: 'Listed', value: 1 },
              { name: 'Unknown', value: 2 },
              { name: 'Unlisted', value: 3 },
            ],
            control: 'listednessCore',
          },
          {
            promptId: '',
            promptName: 'Company Causality',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Company Causality',
            group: false,
            groupItems: [],
            value: [
              { name: 'Almost Certain', value: 1 },
              { name: 'None', value: 2 },
              { name: 'Not Related', value: 3 },
              { name: 'Not Reported', value: 4 },
              { name: 'Possible', value: 5 },
              { name: 'Probable', value: 6 },
              { name: 'Unknown', value: 7 },
              { name: 'Unlikely', value: 8 },
            ],
            control: 'companyCausality',
          },
          {
            promptId: '',
            promptName: 'Listedness (calculated)',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Listedness (calculated)',
            group: false,
            groupItems: [],
            value: [
              { name: 'Listed', value: 1 },
              { name: 'Unknown', value: 2 },
              { name: 'Unlisted', value: 3 },
            ],
            control: 'listednessCalculated',
          },
        ],
      },
    ],
  },
  {
    tabName: 'Analysis',
    control: 'analysisInfo',
    items: [
      {
        sectionName: 'Analysis',
        subItems: [
          {
            promptId: '',
            promptName: 'Case Listedness',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Case Listedness',
            group: false,
            groupItems: [],
            value: [
              { name: 'Listed', value: 1 },
              { name: 'Unlisted', value: 2 },
              { name: 'All', value: 3 },
              { name: 'Unknown', value: 4 },
            ],
            control: 'caseListedness',
          },
          {
            promptId: '',
            promptName: 'Case Outcomes',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Case Outcomes',
            group: false,
            groupItems: [],
            value: [
              { name: 'Abortion due to AE/Infection', value: 1 },
              { name: 'Congenital Anomaly', value: 2 },
              { name: 'Death due to AE/infection', value: 3 },
              { name: 'Death not due to AE/infection', value: 4 },
              { name: 'Fatal', value: 5 },
              { name: 'Improved', value: 6 },
              { name: 'Lasting Damage', value: 7 },
              { name: 'Not Reported', value: 8 },
              { name: 'Recovered', value: 9 },
              { name: 'Recovered with Treatment', value: 10 },
              { name: 'Resolved', value: 11 },
              { name: 'Unchanged', value: 12 },
              { name: 'Unknown', value: 13 },
              { name: 'Worsened', value: 14 },
            ],
            control: 'caseOutcomes',
          },
          {
            promptId: '',
            promptName: 'Case Relatedness',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Case Relation',
            group: false,
            groupItems: [],
            value: [
              { name: 'Related', value: 1 },
              { name: 'Not Related', value: 2 },
              { name: 'All', value: 3 },
              { name: 'Unknown', value: 4 },
            ],
            control: 'caseRelatedness',
          },
          {
            promptId: '',
            promptName: 'Case Seriousness',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Case Seriousness',
            group: false,
            groupItems: [],
            value: [
              { name: 'Serious', value: 1 },
              { name: 'Not Serious', value: 2 },
              { name: 'All', value: 3 },
            ],
            control: 'caseSeriousness',
          },
        ],
      },
    ],
  },
  {
    tabName: 'Additional Information',
    control: 'additionalInfo',
    items: [
      {
        sectionName: 'Reference',
        subItems: [
          {
            promptId: '',
            promptName: 'Reference Type',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Reference Type',
            group: false,
            groupItems: [],
            value: [
              { name: 'BfArM Report Number', value: 1 },
              { name: 'Companion Case', value: 2 },
              { name: 'DEC ID', value: 3 },
              { name: 'E2B Authority Number', value: 4 },
              { name: 'E2B Company Number', value: 5 },
              { name: 'E2B GP Medical No.', value: 6 },
              { name: 'E2B Hospital Record No.', value: 7 },
              { name: 'E2B Linked Report', value: 8 },
              { name: 'E2B Other Number', value: 9 },
              { name: 'E2B Report Duplicate', value: 10 },
              { name: 'E2B Specialist No.', value: 11 },
              { name: 'EMEA Report Number', value: 12 },
              { name: 'EUDAMED FSCA Ref. No.', value: 13 },
              { name: 'EUDAMED Reference No.', value: 14 },
              { name: 'HTTP/URL Reference', value: 15 },
              { name: 'Health Canada File Number', value: 16 },
              { name: 'Historical Ref.', value: 17 },
              { name: 'Local Event Number', value: 18 },
              { name: 'MHLW Completion Report ID', value: 19 },
              { name: 'MHLW Identical Case Num', value: 20 },
              { name: 'MHLW Registration ID', value: 21 },
              { name: 'MHRA Report Number', value: 22 },
              { name: 'MW 3500A Mfr. Rpt. #', value: 23 },
              { name: 'Mfr FSCA Ref. No.', value: 24 },
              { name: 'NCA local FSCA Ref. No.', value: 25 },
              { name: 'Other EUDAMED Ref. No.', value: 26 },
              { name: 'Other Mfr Ref. No.', value: 27 },
              { name: 'Other NCA Local Ref. No.', value: 28 },
              { name: 'PEI Report Number', value: 29 },
              { name: 'PMDA Document Number', value: 30 },
              { name: 'Parent-Child Link', value: 31 },
              { name: 'Patient Link', value: 32 },
              { name: 'Regulatory Ref.', value: 33 },
              { name: 'Source Case', value: 34 },
              { name: 'Spanish Local Id', value: 35 },
            ],
            control: 'referenceType',
          },
        ],
      },
    ],
  },
  {
    tabName: 'Regulatory Reports',
    control: 'regulatoryReportsInfo',
    items: [
      {
        sectionName: 'Regulatory Reports',
        subItems: [
          {
            promptId: '',
            promptName: 'Report Due Date',
            type: 'group',
            group: true,
            groupItems: [
              {
                promptId: '',
                promptName: 'Report Due Date - Start Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select Start Date',
                control: 'reportDueDateStartDate',
              },
              {
                promptId: '',
                promptName: 'Report Due Date - End Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select End Date',
                control: 'reportDueDateEndDate',
              },
            ],
          },
          {
            promptId: '',
            promptName: 'Report Submission Date',
            type: 'group',
            group: true,
            groupItems: [
              {
                promptId: '',
                promptName: 'Report Submission Date - Start Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select Start Date',
                control: 'reportSubmissionStartDate',
              },
              {
                promptId: '',
                promptName: 'Report Submission Date - End Date',
                type: 'calendar',
                filter: false,
                grid: false,
                placeholder: 'Select End Date',
                control: 'reportSubmissionEndDate',
              },
            ],
          },
          {
            promptId: '',
            promptName: 'Report Responsible Group',
            type: 'dropdown',
            filter: false,
            grid: false,
            placeholder: 'Select Report Responsible Group',
            group: false,
            groupItems: [],
            value: [
              { name: 'Administrator Group', value: 1 },
              { name: 'Bookin', value: 2 },
              { name: 'Bookin_J', value: 3 },
              { name: 'Data Entry/Case Assess', value: 4 },
              { name: 'Data Entry/Case Assess_J', value: 5 },
              { name: 'Distribution Closure', value: 6 },
              { name: 'Distribution Closure_J', value: 7 },
              { name: 'Investigator Group', value: 8 },
              { name: 'Medical Review', value: 9 },
              { name: 'Medical Review_J', value: 10 },
              { name: 'Quality Control', value: 11 },
              { name: 'Quality Control_J', value: 12 },
            ],
            control: 'reportResponsibleGroup',
          },
          {
            promptId: '',
            promptName: 'Reporting Destination',
            type: 'dropdown',
            filter: false,
            grid: false,
            group: false,
            groupItems: [],
            placeholder: 'Select Destination',
            value: [
              { name: 'EMEA', value: 1 },
              { name: 'PMDA R3', value: 2 },
              { name: 'US FDA', value: 3 },
            ],
            control: 'reportingDestination',
          },
        ],
      },
    ],
  },
];
