import { URL_ROUTES } from 'src/app/common/constants/routing';

export const ROUTES = [
  {
    path: URL_ROUTES.DASHBOARD,
    label: 'navItems.home',
    icon: 'pi pi-home',
    isActive: false,
    status: true,
    userMandate: true,
    mandate: true,
    permission: 'dashboard',
  },
  {
    status: false,
    icon: 'pi pi-sitemap',
    toggleState: false,
    title: 'navItems.systemManagement',
    items: [
      {
        path: URL_ROUTES.SITE,
        label: 'navItems.sManagement.sites',
        icon: 'ci ci-site-nav',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'site',
      },
      {
        path: URL_ROUTES.CLIENT,
        label: 'navItems.sManagement.clients',
        icon: 'ci ci-client-nav',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'clients',
      },
      {
        path: URL_ROUTES.SUPER_ADMIN,
        label: 'navItems.sManagement.superAdmins',
        icon: 'ci ci-super-admin',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'super-admin',
      },
      {
        path: URL_ROUTES.ADMIN,
        label: 'navItems.sManagement.clientAdmins',
        icon: 'ci ci-admin-nav',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'client-admin',
      },
      {
        path: URL_ROUTES.ROLE,
        label: 'navItems.sManagement.roles',
        icon: 'ci ci-role-nav',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'roles',
      },
      {
        path: URL_ROUTES.USER_GROUPS,
        label: 'navItems.sManagement.userGroups',
        icon: 'ci ci-users-nav',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'user-group',
      },
      {
        path: URL_ROUTES.USER,
        label: 'navItems.sManagement.users',
        icon: 'pi pi-users',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'users',
      },
    ],
  },
  {
    status: false,
    icon: 'pi pi-bolt',
    toggleState: false,
    title: 'navItems.Querying',
    items: [
      {
        path: URL_ROUTES.QUERY_BY_EXAMPLE_FORM,
        label: 'navItems.query.qbe',
        icon: 'ci ci-qbe',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'query-by-example',
      },
      {
        path: URL_ROUTES.QUERY_BY_SQL,
        label: 'navItems.query.qbSQL',
        icon: 'ci ci-qbs',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'query-by-sql',
      },
      {
        path: URL_ROUTES.QUERY_LIBRARY,
        label: 'navItems.query.qLibrary',
        icon: 'ci ci-ql',
        isActive: false,
        status: false,
        userMandate: true,
        mandate: false,
        permission: 'query-listing,query-by-sql,query-by-example',
      },
    ],
  },
  {
    status: false,
    icon: 'pi pi-book',
    toggleState: false,
    title: 'navItems.CaseSeries',
    items: [
      {
        path: URL_ROUTES.MANUAL_CASE_SERIES,
        label: 'navItems.caseSeries.manual',
        icon: 'ci ci-mcs',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'manual-case-series',
      },
      {
        path: URL_ROUTES.CASE_SERIES_OPERATION,
        label: 'navItems.caseSeries.cso',
        icon: 'ci ci-cso',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'case-series-operation',
      },
      {
        path: URL_ROUTES.CASE_SERIES_LIBRARY,
        label: 'navItems.caseSeries.csLibrary',
        icon: 'ci ci-ql',
        isActive: false,
        status: false,
        userMandate: true,
        mandate: false,
        permission:
          'case-series-listing,case-series-operation,manual-case-series',
      },
    ],
  },
  {
    label: 'navItems.Report',
    path: URL_ROUTES.REPORTING,
    icon: 'ci ci-report',
    isActive: false,
    permission: 'reports',
    status: false,
    userMandate: false,
    mandate: false,
  },
  {
    status: false,
    icon: 'ci ci-report',
    toggleState: false,
    title: 'navItems.reporting',
    items: [
      {
        label: 'navItems.reports.webReport',
        icon: 'ci ci-web-report',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        path: URL_ROUTES.WEB_REPORTING,
        isReportUrl: false,
        reportUrl: '',
        permission: 'web-report',
      },
      {
        label: 'navItems.reports.pageReport',
        icon: 'ci ci-page-report',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        path: URL_ROUTES.PAGE_REPORTING,
        isReportUrl: false,
        reportUrl: '',
        permission: 'page-report',
      },
      {
        label: 'navItems.reports.reportLibrary',
        icon: 'ci ci-report-library ',
        isActive: false,
        status: false,
        userMandate: true,
        mandate: false,
        path: URL_ROUTES.REPORTING_LIBRARY,
        isReportUrl: false,
        reportUrl: '',
        permission: 'report-library',
      },
    ],
  },
  {
    label: 'navItems.visualizations',
    path: URL_ROUTES.COMPOSER,
    icon: 'ci ci-dash-composer',
    isActive: false,
    permission: 'visualizations',
    status: false,
  },
  {
    status: false,
    icon: 'ci ci-analytics',
    toggleState: false,
    title: 'navItems.analytics',
    items: [
      {
        path: URL_ROUTES.QUICK_SIGHT_VIEW,
        label: 'navItems.dataAnalytics',
        icon: 'ci ci-data-analytics',
        isActive: false,
        status: false,
        userMandate: false,
        mandate: false,
        permission: 'user-quicksight',
      },
      // {
      //   path: URL_ROUTES.QUICK_SIGHT_SEARCH,
      //   label: 'navItems.quicksightSearch',
      //   icon: 'ci ci-quicksight-search',
      //   isActive: false,
      //   status: false,
      // userMandate: true,
      // mandate: false,
      //   permission: '',
      // },
    ],
  },
  {
    label: 'navItems.auditLogs',
    path: URL_ROUTES.AUDIT_LOG,
    icon: 'pi pi-history',
    isActive: false,
    status: false,
    userMandate: false,
    mandate: false,
    permission: 'audit-log',
  },
  {
    label: 'navItems.settings',
    path: URL_ROUTES.SETTINGS,
    icon: 'pi pi-cog',
    isActive: false,
    status: false,
    userMandate: false,
    mandate: false,
    permission: 'app-settings',
  },
];

export const FOOTER_BUTTON_ROUTES = [
  {
    path: URL_ROUTES.PROFILE,
    label: 'navItems.myProfile',
    icon: 'pi pi-id-card',
    isActive: false,
    status: true,
    userMandate: false,
    mandate: true,
    permission: 'profile',
    // color: 'text-green-400',
  },
  {
    path: URL_ROUTES.HELP_USER_MANUAL,
    label: 'navItems.help',
    icon: 'pi pi-question-circle',
    isActive: false,
    status: true,
    userMandate: false,
    mandate: true,
    // color: 'text-yellow-400',
  },
  {
    path: URL_ROUTES.LOGIN,
    label: 'navItems.logout',
    icon: 'pi pi-sign-out',
    isActive: false,
    status: true,
    userMandate: false,
    mandate: true,
    // color: 'text-red-900',
  },
];
